spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/dill?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    tomcat:
      initial-size: 20
      min-idle: 10
      max-active: 100
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

